import type { Metadata } from "next";
import "./globals.css";
import { Londrina_Sketch } from "next/font/google";
 
// If loading a variable font, you don't need to specify the font weight
const londrina = Londrina_Sketch({
  subsets: ['latin'],
  display: 'swap',
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={londrina.className}
      >
        {children}
      </body>
    </html>
  );
}
